experience_level: null
job_type: null
keywords: ai engineer
location: null
max_results: 50
time_posted_interval: r86400
url_job: https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/
url_search: https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search
work_type: null
