search_parameters:
- experience_level: null
  geo_id: null
  job_type: P
  keywords: AI Engineer
  time_posted_interval: r86400
  work_type: null
- experience_level: null
  geo_id: null
  job_type: C
  keywords: AI Engineer
  time_posted_interval: r86400
  work_type: null
- experience_level: null
  geo_id: null
  job_type: F
  keywords: AI Engineer
  time_posted_interval: r86400
  work_type: null
